name: Validation

on:
  workflow_dispatch:
    inputs:
      source:
        required: true
        type: string
      title:
        required: true
        type: string
      source_url:
        required: false
        type: string
      git_coatjava:
        required: false
        type: string
      git_clas12Tags:
        required: false
        type: string
  pull_request:
  push:
    branches: [ master ]

run-name: "[${{ inputs.source || github.repository }}] ${{ inputs.title || github.event.pull_request.title || github.event.push.head_commit.message }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  # default dependency forks and branches
  git_coatjava: '{
    "fork": "JeffersonLab/coatjava",
    "branch": "development"
  }'
  git_clas12Tags: '{
    "fork": "gemc/clas12Tags",
    "branch": "main"
  }'

jobs:

  # dependency and triggerer info
  #############################################################################
  dependency_info:
    runs-on: ubuntu-latest
    outputs:
      fork_coatjava: ${{ steps.info.outputs.fork_coatjava }}
      branch_coatjava: ${{ steps.info.outputs.branch_coatjava }}
      fork_clas12Tags: ${{ steps.info.outputs.fork_clas12Tags }}
      branch_clas12Tags: ${{ steps.info.outputs.branch_clas12Tags }}
    steps:
      - name: get dependency info
        id: info
        run: |
          echo fork_coatjava=$(     echo '${{ inputs.git_coatjava || env.git_coatjava }}'     | jq -r '.fork'   ) >> $GITHUB_OUTPUT
          echo branch_coatjava=$(   echo '${{ inputs.git_coatjava || env.git_coatjava }}'     | jq -r '.branch' ) >> $GITHUB_OUTPUT
          echo fork_clas12Tags=$(   echo '${{ inputs.git_clas12Tags || env.git_clas12Tags }}' | jq -r '.fork'   ) >> $GITHUB_OUTPUT
          echo branch_clas12Tags=$( echo '${{ inputs.git_clas12Tags || env.git_clas12Tags }}' | jq -r '.branch' ) >> $GITHUB_OUTPUT
      - name: dispatch summary
        run: |
          echo '| | | |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| **Pull Request** | <${{ inputs.source_url || github.event.pull_request.html_url }}> | ${{ inputs.title || github.event.pull_request.title }} |' >> $GITHUB_STEP_SUMMARY
          echo '| **`coatjava` Fork and Branch** | `${{ steps.info.outputs.fork_coatjava }}` | [`${{ steps.info.outputs.branch_coatjava }}`](https://github.com/${{ steps.info.outputs.fork_coatjava }}/tree/${{ steps.info.outputs.branch_coatjava }}) |' >> $GITHUB_STEP_SUMMARY
          echo '| **`clas12Tags` Fork and Branch** | `${{ steps.info.outputs.fork_clas12Tags }}` | [`${{ steps.info.outputs.branch_clas12Tags }}`](https://github.com/${{ steps.info.outputs.fork_clas12Tags }}/tree/${{ steps.info.outputs.branch_clas12Tags }}) |' >> $GITHUB_STEP_SUMMARY
          echo '| | | |' >> $GITHUB_STEP_SUMMARY

  # build
  #############################################################################

  build_coatjava:
    needs:
      - dependency_info
    runs-on: ubuntu-latest
    steps:
    - name: setup java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - name: clone
      run: git clone https://github.com/${{ needs.dependency_info.outputs.fork_coatjava }}.git --branch ${{ needs.dependency_info.outputs.branch_coatjava }}
    - name: build
      run: |
        cd coatjava
        ./build-coatjava.sh
    - name: tree
      run: tree
    - name: tar
      run: tar czvf coatjava{.tar.gz,}
    - uses: actions/upload-artifact@v3
      with:
        name: build
        retention-days: 1
        path: ./*.tar.gz

  build_gemc:
    needs:
      - dependency_info
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:4.4.2-5.1-5.2-5.3-fedora36-cvmfs ##### FIXME: need `latest` tag
    steps:
    - name: clone
      run: git clone https://github.com/${{ needs.dependency_info.outputs.fork_clas12Tags }}.git --branch ${{ needs.dependency_info.outputs.branch_clas12Tags }}
    - name: build
      run: |
        source /app/localSetup.sh
        cd clas12Tags/source
        scons -j2 OPT=1
    - name: tar
      run: tar czvf clas12Tags{.tar.gz,}
    - uses: actions/upload-artifact@v3
      with:
        name: build
        retention-days: 1
        path: ./*.tar.gz

  # event generation
  #############################################################################
  event_generation:
    needs:
      - build_coatjava
    runs-on: ubuntu-latest
    steps:
    - name: setup java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - name: setup groovy
      uses: wtfjoke/setup-groovy@v1
      with:
        groovy-version: 4.x
    - uses: actions/download-artifact@v3
      with:
        name: build
    - name: untar build
      run: tar xzvf *.tar.gz
    - name: event generation
      run: |
        coatjava/validation/advanced-tests/src/eb/scripts/gen.sh
    - uses: actions/upload-artifact@v3
      with:
        name: event_generation
        retention-days: 1
        path: ./*.txt

  # simulation
  #############################################################################
  simulation:
    needs:
      - event_generation
      - build_gemc
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:4.4.2-5.1-5.2-5.3-fedora36-cvmfs ##### FIXME: need `latest` tag
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: event_generation
    - uses: actions/download-artifact@v3
      with:
        name: build
    - name: tree
      run: ls -lR
    - name: untar build
      run: tar xzvf *.tar.gz
    - name: simulation
      run: |
        source /app/localSetup.sh
        cd clas12Tags/source
        ./gemc # TODO
