name: Scheduled Test

on:
  schedule:
    # Sun, Tue, Thu, at 0830Z
    - cron: '30 8 * * 0,2,4'

jobs:

  validation:
    uses: ./.github/workflows/ci.yml
    with:
      num_events: 1000
      matrix_evgen: >-
        [
          "e_K",
          "e_KC",
          "e_n",
          "e_g",
          "e_nC",
          "eFT_K",
          "e_gFT"
        ]
      matrix_config: >-
        [
          "clas12-default",
          "rga_spring2018",
          "rga_fall2018",
          "rgk_fall2018_FTOn",
          "rgb_fall2019",
          "rgc_summer2022"
        ]

  issue_bot:
    name: Issue bot
    if: ${{ github.event_name == 'schedule' && ( cancelled() || failure() ) }}
    runs-on: ubuntu-latest
    needs: [ validation ]
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: ${{ github.event.repository.html_url }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/scheduled-issue.md
