name: Scheduled Test

on:
  schedule:
    - cron: '33 8 * * *'

jobs:

  validation:
    uses: ./.github/workflows/ci.yml
    with:
      num_events: 1000

  issue_bot:
    name: Issue bot
    if: ${{ github.event_name == 'schedule' && ( cancelled() || failure() ) }}
    runs-on: ubuntu-latest
    needs: [ validation ]
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: ${{ github.event.repository.html_url }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/nightly-issue.md
